//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18010
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportMySportWebServiceClient.SmsWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://competitionresults.sms.org/", ConfigurationName="SmsWebService.CompetitionsResultsWS")]
    public interface CompetitionsResultsWS {
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname liga aus Namespace  nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://competitionresults.sms.org/CompetitionsResultsWS/isCompetitionCompletedReq" +
            "uest", ReplyAction="http://competitionresults.sms.org/CompetitionsResultsWS/isCompetitionCompletedRes" +
            "ponse")]
        SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedResponse isCompetitionCompleted(SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://competitionresults.sms.org/CompetitionsResultsWS/isCompetitionCompletedReq" +
            "uest", ReplyAction="http://competitionresults.sms.org/CompetitionsResultsWS/isCompetitionCompletedRes" +
            "ponse")]
        System.Threading.Tasks.Task<SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedResponse> isCompetitionCompletedAsync(SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname id aus Namespace  nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://competitionresults.sms.org/CompetitionsResultsWS/getCompetitionByIdRequest" +
            "", ReplyAction="http://competitionresults.sms.org/CompetitionsResultsWS/getCompetitionByIdRespons" +
            "e")]
        SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdResponse getCompetitionById(SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://competitionresults.sms.org/CompetitionsResultsWS/getCompetitionByIdRequest" +
            "", ReplyAction="http://competitionresults.sms.org/CompetitionsResultsWS/getCompetitionByIdRespons" +
            "e")]
        System.Threading.Tasks.Task<SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdResponse> getCompetitionByIdAsync(SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequest request);
        
        // CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname liga aus Namespace  nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://competitionresults.sms.org/CompetitionsResultsWS/getCompetitionResultsRequ" +
            "est", ReplyAction="http://competitionresults.sms.org/CompetitionsResultsWS/getCompetitionResultsResp" +
            "onse")]
        SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsResponse getCompetitionResults(SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://competitionresults.sms.org/CompetitionsResultsWS/getCompetitionResultsRequ" +
            "est", ReplyAction="http://competitionresults.sms.org/CompetitionsResultsWS/getCompetitionResultsResp" +
            "onse")]
        System.Threading.Tasks.Task<SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsResponse> getCompetitionResultsAsync(SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isCompetitionCompletedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isCompetitionCompleted", Namespace="http://competitionresults.sms.org/", Order=0)]
        public SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequestBody Body;
        
        public isCompetitionCompletedRequest() {
        }
        
        public isCompetitionCompletedRequest(SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class isCompetitionCompletedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string liga;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sport;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string datum;
        
        public isCompetitionCompletedRequestBody() {
        }
        
        public isCompetitionCompletedRequestBody(string liga, string sport, string datum) {
            this.liga = liga;
            this.sport = sport;
            this.datum = datum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isCompetitionCompletedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isCompetitionCompletedResponse", Namespace="http://competitionresults.sms.org/", Order=0)]
        public SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedResponseBody Body;
        
        public isCompetitionCompletedResponse() {
        }
        
        public isCompetitionCompletedResponse(SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class isCompetitionCompletedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public isCompetitionCompletedResponseBody() {
        }
        
        public isCompetitionCompletedResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCompetitionByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCompetitionById", Namespace="http://competitionresults.sms.org/", Order=0)]
        public SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequestBody Body;
        
        public getCompetitionByIdRequest() {
        }
        
        public getCompetitionByIdRequest(SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCompetitionByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public getCompetitionByIdRequestBody() {
        }
        
        public getCompetitionByIdRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCompetitionByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCompetitionByIdResponse", Namespace="http://competitionresults.sms.org/", Order=0)]
        public SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdResponseBody Body;
        
        public getCompetitionByIdResponse() {
        }
        
        public getCompetitionByIdResponse(SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCompetitionByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCompetitionByIdResponseBody() {
        }
        
        public getCompetitionByIdResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCompetitionResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCompetitionResults", Namespace="http://competitionresults.sms.org/", Order=0)]
        public SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequestBody Body;
        
        public getCompetitionResultsRequest() {
        }
        
        public getCompetitionResultsRequest(SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCompetitionResultsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string liga;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sport;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string datum;
        
        public getCompetitionResultsRequestBody() {
        }
        
        public getCompetitionResultsRequestBody(string liga, string sport, string datum) {
            this.liga = liga;
            this.sport = sport;
            this.datum = datum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCompetitionResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCompetitionResultsResponse", Namespace="http://competitionresults.sms.org/", Order=0)]
        public SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsResponseBody Body;
        
        public getCompetitionResultsResponse() {
        }
        
        public getCompetitionResultsResponse(SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCompetitionResultsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCompetitionResultsResponseBody() {
        }
        
        public getCompetitionResultsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompetitionsResultsWSChannel : SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompetitionsResultsWSClient : System.ServiceModel.ClientBase<SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS>, SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS {
        
        public CompetitionsResultsWSClient() {
        }
        
        public CompetitionsResultsWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompetitionsResultsWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompetitionsResultsWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompetitionsResultsWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedResponse SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS.isCompetitionCompleted(SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequest request) {
            return base.Channel.isCompetitionCompleted(request);
        }
        
        public string isCompetitionCompleted(string liga, string sport, string datum) {
            SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequest inValue = new SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequest();
            inValue.Body = new SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequestBody();
            inValue.Body.liga = liga;
            inValue.Body.sport = sport;
            inValue.Body.datum = datum;
            SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedResponse retVal = ((SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS)(this)).isCompetitionCompleted(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedResponse> SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS.isCompetitionCompletedAsync(SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequest request) {
            return base.Channel.isCompetitionCompletedAsync(request);
        }
        
        public System.Threading.Tasks.Task<SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedResponse> isCompetitionCompletedAsync(string liga, string sport, string datum) {
            SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequest inValue = new SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequest();
            inValue.Body = new SupportMySportWebServiceClient.SmsWebService.isCompetitionCompletedRequestBody();
            inValue.Body.liga = liga;
            inValue.Body.sport = sport;
            inValue.Body.datum = datum;
            return ((SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS)(this)).isCompetitionCompletedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdResponse SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS.getCompetitionById(SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequest request) {
            return base.Channel.getCompetitionById(request);
        }
        
        public string getCompetitionById(string id) {
            SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequest inValue = new SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequest();
            inValue.Body = new SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequestBody();
            inValue.Body.id = id;
            SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdResponse retVal = ((SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS)(this)).getCompetitionById(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdResponse> SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS.getCompetitionByIdAsync(SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequest request) {
            return base.Channel.getCompetitionByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdResponse> getCompetitionByIdAsync(string id) {
            SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequest inValue = new SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequest();
            inValue.Body = new SupportMySportWebServiceClient.SmsWebService.getCompetitionByIdRequestBody();
            inValue.Body.id = id;
            return ((SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS)(this)).getCompetitionByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsResponse SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS.getCompetitionResults(SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequest request) {
            return base.Channel.getCompetitionResults(request);
        }
        
        public string getCompetitionResults(string liga, string sport, string datum) {
            SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequest inValue = new SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequest();
            inValue.Body = new SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequestBody();
            inValue.Body.liga = liga;
            inValue.Body.sport = sport;
            inValue.Body.datum = datum;
            SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsResponse retVal = ((SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS)(this)).getCompetitionResults(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsResponse> SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS.getCompetitionResultsAsync(SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequest request) {
            return base.Channel.getCompetitionResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsResponse> getCompetitionResultsAsync(string liga, string sport, string datum) {
            SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequest inValue = new SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequest();
            inValue.Body = new SupportMySportWebServiceClient.SmsWebService.getCompetitionResultsRequestBody();
            inValue.Body.liga = liga;
            inValue.Body.sport = sport;
            inValue.Body.datum = datum;
            return ((SupportMySportWebServiceClient.SmsWebService.CompetitionsResultsWS)(this)).getCompetitionResultsAsync(inValue);
        }
    }
}
