package CORBA_Competitions;


/**
* CORBA_Competitions/CompetitionsResults.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GetCompetitionResults.idl
* Samstag, 17. November 2012 09:17 Uhr MEZ
*/

public interface CompetitionsResults extends CompetitionsResultsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CompetitionsResults
