package CORBA_Competitions;


/**
* CORBA_Competitions/CompetitionsResultsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GetCompetitionResults.idl
* Samstag, 17. November 2012 09:17 Uhr MEZ
*/

public interface CompetitionsResultsOperations 
{
  String getCompetitionResults (String liga, String sport, String datum);
} // interface CompetitionsResultsOperations
