/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CommunicationInterfaces.ClubMemberDTO;
import CommunicationInterfaces.DepartmentDTO;
import CommunicationInterfaces.TeamDTO;
import java.rmi.RemoteException;
import java.util.Collection;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Johannes
 */
public class MitgliederZuTeamFrame extends javax.swing.JFrame {

    private TeamDTO selectedTeam;
    private static Collection<TeamDTO> allTeamsOfDepartment;
    private HashSet<TeamDTO> changedTeams = new HashSet<TeamDTO>();

    /**
     * Creates new form MitgliederZuTeamFrame
     */
    public MitgliederZuTeamFrame() {
        initComponents();
        try {
            DepartmentDTO dep = GUIController.getDepartmentOfLoggedInDepartmentChief();
            Collection<TeamDTO> depTeams = GUIController.getDepartmentController().getAllTeamsOfDepartment(dep.getId());
            if (depTeams != null) {
                allTeamsOfDepartment = depTeams;
            } else {
                System.out.println("Error");
                allTeamsOfDepartment = new LinkedList<TeamDTO>();
            }
        } catch (RemoteException ex) {
            Logger.getLogger(MitgliederZuTeamFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        comboTeam.removeAllItems();
        comboTeam.addItem("<select Team>");
        for (TeamDTO teamDTO : allTeamsOfDepartment) {
            comboTeam.addItem(teamDTO);
        }
        tableTeamMembers.setEnabled(false);
        tableAllMembers.setEnabled(false);
        buttonAdd.setEnabled(false);
        buttonRemove.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAllMembers = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTeamMembers = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboTeam = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buttonRemove.setText("<<");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        tableAllMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Vorname", "Nachname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableAllMembers);

        tableTeamMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Vorname", "Nachname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTeamMembers);

        buttonAdd.setText(">>");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        jLabel1.setText("Team:");

        comboTeam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTeamActionPerformed(evt);
            }
        });

        jLabel2.setText("Verfügbare Mitglieder");

        jLabel3.setText("Teammitglieder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        removeRight();
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        removeLeft();
    }//GEN-LAST:event_buttonAddActionPerformed

    private void comboTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTeamActionPerformed
        try {
            if (selectedTeam != null) {
                //früher mal gabs hier coolen code
            } else {
                tableTeamMembers.setEnabled(true);
                tableAllMembers.setEnabled(true);
                buttonAdd.setEnabled(true);
                buttonRemove.setEnabled(true);
            }
            Object o = comboTeam.getSelectedItem();
            if (o instanceof TeamDTO) {
                selectedTeam = (TeamDTO) o;
                changedTeams.add(selectedTeam);
                fillTables();
            }
        } catch (RemoteException ex) {
            Logger.getLogger(MitgliederZuTeamFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboTeamActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        speichern();

    }//GEN-LAST:event_formWindowClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JComboBox comboTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableAllMembers;
    private javax.swing.JTable tableTeamMembers;
    // End of variables declaration//GEN-END:variables

    private void removeRight() {
        if (tableTeamMembers.getSelectedRowCount() != 0) {
            MemberTableModel modelLeft = (MemberTableModel) tableAllMembers.getModel();
            MemberTableModel modelRight = (MemberTableModel) tableTeamMembers.getModel();
            int[] is = tableTeamMembers.getSelectedRows();
            LinkedList<ClubMemberDTO> removs = new LinkedList<ClubMemberDTO>();
            for (int i : is) {
                int rowindex = tableTeamMembers.convertRowIndexToModel(i);
                removs.add(modelRight.getMember(rowindex));

            }
            for (ClubMemberDTO member : removs) {
                modelRight.members.remove(member);
                modelLeft.addMember(member);
            }
            modelLeft.fireTableDataChanged();
            modelRight.fireTableDataChanged();
        }
    }

    private void removeLeft() {
        int[] is = tableAllMembers.getSelectedRows();

        if (tableAllMembers.getSelectedRowCount() != 0) {
            LinkedList<ClubMemberDTO> removs = new LinkedList<ClubMemberDTO>();
            MemberTableModel modelLeft = (MemberTableModel) tableAllMembers.getModel();
            MemberTableModel modelRight = (MemberTableModel) tableTeamMembers.getModel();
            for (int i : is) {
                int rowindex = tableAllMembers.convertRowIndexToModel(i);

                removs.add(modelLeft.getMember(rowindex));
            }
            for (ClubMemberDTO member : removs) {
                modelRight.addMember(member);
                modelLeft.members.remove(member);
            }
            modelLeft.fireTableDataChanged();
            modelRight.fireTableDataChanged();
        }
    }

    private void speichern() {
        for (TeamDTO team : changedTeams) {
            try {
                System.out.println(team.getTeamName());
                GUIController.getDepartmentController().updateTeam(team);
            } catch (RemoteException ex) {
                Logger.getLogger(MitgliederZuTeamFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void fillTables() throws RemoteException {
        if (selectedTeam != null) {
            Collection<ClubMemberDTO> teamMembers = selectedTeam.getAllClubMembers();
            tableTeamMembers.setModel(new MemberTableModel(teamMembers));
            Collection<ClubMemberDTO> allMembers = GUIController.getClubMemberController().getAllClubMembers();
            LinkedList<ClubMemberDTO> removeMemver = new LinkedList<ClubMemberDTO>();
            for (ClubMemberDTO dto : allMembers) {
                if (teamMembers.contains(dto)) {
                    removeMemver.add(dto);
                }
            }
            for (ClubMemberDTO member : removeMemver) {
                allMembers.remove(member);
            }
            tableAllMembers.setModel(new MemberTableModel(allMembers));
        }
    }

    private class MemberTableModel extends AbstractTableModel {

        private Collection<ClubMemberDTO> members;

        public MemberTableModel(Collection<ClubMemberDTO> members) {
            this.members = members;
        }

        @Override
        public String getColumnName(int col) {
            switch (col) {
                case 0:
                    return "Vorname";
                case 1:
                    return "Nachname";
                default:
                    return "";
            }
        }

        @Override
        public int getRowCount() {
            return members.size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            ClubMemberDTO m = (ClubMemberDTO) members.toArray()[rowIndex];
            if (m != null) {
                switch (columnIndex) {
                    case 0:
                        return m.getFirstname();
                    case 1:
                        return m.getLastname();
                    default:
                        return "";
                }
            }
            return "";
        }

        public ClubMemberDTO removeMember(int row) {
            ClubMemberDTO member = (ClubMemberDTO) members.toArray()[row];
            members.remove(member);
            return member;
        }

        public ClubMemberDTO getMember(int index) {
            return (ClubMemberDTO) members.toArray()[index];
        }

        public void addMember(ClubMemberDTO member) {
            members.add(member);
        }
    }
}
