/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CommunicationInterfaces.CompetitionDTO;
import CommunicationInterfaces.CompetitionTeamDTO;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Johannes
 */
public class SportlerMessagePanel extends javax.swing.JPanel {

    /**
     * Creates new form MessagePanel
     */
    private MessageGUI prev;
    private CompetitionDTO message;

    public SportlerMessagePanel(MessageGUI prev, CompetitionDTO message) {
        initComponents();
        this.prev = prev;
        this.message = message;
        textFieldDatum.setText(message.getDateOfCompetition().toString());
        textFieldWettkampf.setText(message.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonZusagen = new javax.swing.JButton();
        buttonAbsagen = new javax.swing.JButton();
        textFieldDatum = new javax.swing.JTextField();
        textFieldWettkampf = new javax.swing.JTextField();

        jLabel1.setText("Wettkampf:");

        jLabel2.setText("Datum:");

        buttonZusagen.setText("Zusagen");
        buttonZusagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZusagenActionPerformed(evt);
            }
        });

        buttonAbsagen.setText("Absagen");
        buttonAbsagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbsagenActionPerformed(evt);
            }
        });

        textFieldDatum.setEditable(false);

        textFieldWettkampf.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(buttonZusagen)
                        .addGap(38, 38, 38)
                        .addComponent(buttonAbsagen))
                    .addComponent(textFieldWettkampf, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldWettkampf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonZusagen)
                    .addComponent(buttonAbsagen))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonZusagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZusagenActionPerformed
        prev.removeMessage(message);
        prev.selectNR1();
    }//GEN-LAST:event_buttonZusagenActionPerformed

    private void buttonAbsagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbsagenActionPerformed
        try {
            for (CompetitionTeamDTO compTeamDTO : message.getAllTeamsOfCompetition()) {
                if ((compTeamDTO.getClubMember().getId() == GUIController.getLoggedInMember().getId()) && (compTeamDTO.getCompetition().getId() == message.getId())) {
                    message.getAllTeamsOfCompetition().remove(compTeamDTO);
                }
            }
            GUIController.getCompetitionController().updateCompetition(message);
            prev.removeMessage(message);
            prev.selectNR1();
        } catch (RemoteException ex) {
            Logger.getLogger(SportlerMessagePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonAbsagenActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbsagen;
    private javax.swing.JButton buttonZusagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textFieldDatum;
    private javax.swing.JTextField textFieldWettkampf;
    // End of variables declaration//GEN-END:variables
}
