package Persistence;
// Generated 11.11.2012 20:07:48 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompetitionTeamId generated by hbm2java
 */
@Embeddable
public class CompetitionTeamId implements java.io.Serializable {

    private int teamId;
    private int clubMemberId;

    public CompetitionTeamId() {
    }

    public CompetitionTeamId(int teamId, int clubMemberId) {
        this.teamId = teamId;
        this.clubMemberId = clubMemberId;
    }

    @Column(name = "team_id", nullable = false)
    public int getTeamId() {
        return this.teamId;
    }

    public void setTeamId(int teamId) {
        this.teamId = teamId;
    }

    @Column(name = "clubMember_id", nullable = false)
    public int getClubMemberId() {
        return this.clubMemberId;
    }

    public void setClubMemberId(int clubMemberId) {
        this.clubMemberId = clubMemberId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof CompetitionTeamId)) {
            return false;
        }
        CompetitionTeamId castOther = (CompetitionTeamId) other;

        return (this.getTeamId() == castOther.getTeamId())
                && (this.getClubMemberId() == castOther.getClubMemberId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getTeamId();
        result = 37 * result + this.getClubMemberId();
        return result;
    }
}
