package Persistence;
// Generated 28.10.2012 20:58:08 by Hibernate Tools 3.2.1.GA

import Persistence.interfaces.ICompetitionTeam;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompetitionTeam generated by hbm2java
 */
@Entity
@Table(name = "CompetitionTeam", catalog = "c1teamf")
public class CompetitionTeam implements ICompetitionTeam {

    private CompetitionTeamId id;
    private Team team;
    private Competition competition;
    private ClubMember clubMember;

    public CompetitionTeam() {
    }

    public CompetitionTeam(CompetitionTeamId id, Team team, Competition competition, ClubMember clubMember) {
        this.id = id;
        this.team = team;
        this.competition = competition;
        this.clubMember = clubMember;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "competitionId", column =
        @Column(name = "competition_id", nullable = false)),
        @AttributeOverride(name = "teamId", column =
        @Column(name = "team_id", nullable = false))})
    @Override
    public CompetitionTeamId getId() {
        return this.id;
    }

    @Override
    public void setId(CompetitionTeamId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "team_id", nullable = false, insertable = false, updatable = false)
    @Override
    public Team getTeam() {
        return this.team;
    }

    @Override
    public void setTeam(Team team) {
        this.team = team;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "competition_id", nullable = false, insertable = false, updatable = false)
    @Override
    public Competition getCompetition() {
        return this.competition;
    }

    @Override
    public void setCompetition(Competition competition) {
        this.competition = competition;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "clubMember_id", nullable = false)
    @Override
    public ClubMember getClubMember() {
        return this.clubMember;
    }

    @Override
    public void setClubMember(ClubMember clubMember) {
        this.clubMember = clubMember;
    }
}
