package Persistence;
// Generated 27.10.2012 15:46:24 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Competition generated by hbm2java
 */
@Entity
@Table(name = "Competition", catalog = "c1teamf")
public class Competition implements java.io.Serializable {

    private Integer id;
    private Department department;
    private String name;
    private double competitionfee;
    private Date date;
    private Set<Match> matchs = new HashSet(0);
    private Set<CompetitionTeam> competitionTeams = new HashSet(0);

    public Competition() {
    }

    public Competition(Department department, String name, double competitionfee, Date date) {
        this.department = department;
        this.name = name;
        this.competitionfee = competitionfee;
        this.date = date;
    }

    public Competition(Department department, String name, double competitionfee, Date date, Set matchs, Set competitionTeams) {
        this.department = department;
        this.name = name;
        this.competitionfee = competitionfee;
        this.date = date;
        this.matchs = matchs;
        this.competitionTeams = competitionTeams;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Department_id", nullable = false)
    public Department getDepartment() {
        return this.department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "competitionfee", nullable = false, precision = 22, scale = 0)
    public double getCompetitionfee() {
        return this.competitionfee;
    }

    public void setCompetitionfee(double competitionfee) {
        this.competitionfee = competitionfee;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date", nullable = false, length = 10)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "competition")
    public Set<Match> getMatchs() {
        return this.matchs;
    }

    public void setMatchs(Set matchs) {
        this.matchs = matchs;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "competition")
    public Set<CompetitionTeam> getCompetitionTeams() {
        return this.competitionTeams;
    }

    public void setCompetitionTeams(Set competitionTeams) {
        this.competitionTeams = competitionTeams;
    }
}
