package Persistence;
// Generated 11.11.2012 20:07:48 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * League generated by hbm2java
 */
@Entity
@Table(name = "League", catalog = "c1teamf", uniqueConstraints =
@UniqueConstraint(columnNames = "name"))
public class League implements java.io.Serializable {

    private Integer id;
    private Sport sport;
    private Federation federation;
    private String name;
    private Set<Team> teams = new HashSet<Team>(0);
    private Set<Team> teams_1 = new HashSet<Team>(0);

    public League() {
    }

    public League(Sport sport, Federation federation, String name) {
        this.sport = sport;
        this.federation = federation;
        this.name = name;
    }

    public League(Sport sport, Federation federation, String name, Set teams, Set teams_1) {
        this.sport = sport;
        this.federation = federation;
        this.name = name;
        this.teams = teams;
        this.teams_1 = teams_1;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "sport_id", nullable = false)
    public Sport getSport() {
        return this.sport;
    }

    public void setSport(Sport sport) {
        this.sport = sport;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "federation_id", nullable = false)
    public Federation getFederation() {
        return this.federation;
    }

    public void setFederation(Federation federation) {
        this.federation = federation;
    }

    @Column(name = "name", unique = true, nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinTable(name = "TeamLeague", catalog = "c1teamf", joinColumns = {
        @JoinColumn(name = "league_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "team_id", nullable = false, updatable = false)})
    public Set<Team> getTeams() {
        return this.teams;
    }

    public void setTeams(Set<Team> teams) {
        this.teams = teams;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "league")
    public Set<Team> getTeams_1() {
        return this.teams_1;
    }

    public void setTeams_1(Set<Team> teams_1) {
        this.teams_1 = teams_1;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final League other = (League) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }
    
    
}
