package Persistence;
// Generated 28.10.2012 20:58:08 by Hibernate Tools 3.2.1.GA

import Persistence.interfaces.ILeague;
import java.util.HashSet;
import java.util.Set;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.*;

/**
 * League generated by hbm2java
 */
@Entity
@Table(name = "League", catalog = "c1teamf", uniqueConstraints =
@UniqueConstraint(columnNames = "name"))
public class League implements ILeague {

    private Integer id;
    private Sport sport;
    private Federation federation;
    private String name;
    private Set<Team> teams = new HashSet<Team>(0);
    private Set<Team> teams_1 = new HashSet<Team>(0);

    public League() {
    }

    public League(Sport sport, Federation federation, String name) {
        this.sport = sport;
        this.federation = federation;
        this.name = name;
    }

    public League(Sport sport, Federation federation, String name, Set<Team> teams, Set<Team> teams_1) {
        this.sport = sport;
        this.federation = federation;
        this.name = name;
        this.teams = teams;
        this.teams_1 = teams_1;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sport_id", nullable = false)
    @Override
    public Sport getSport() {
        return this.sport;
    }

    @Override
    public void setSport(Sport sport) {
        this.sport = sport;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "federation_id", nullable = false)
    @Override
    public Federation getFederation() {
        return this.federation;
    }

    @Override
    public void setFederation(Federation federation) {
        this.federation = federation;
    }

    @Column(name = "name", unique = true, nullable = false, length = 45)
    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "TeamLeague", catalog = "c1teamf", joinColumns = {
        @JoinColumn(name = "league_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "team_id", nullable = false, updatable = false)})
    @Override
    public Set<Team> getTeams() {
        return this.teams;
    }

    @Override
    public void setTeams(Set<Team> teams) {
        this.teams = teams;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "league")
    @Override
    public Set<Team> getTeams_1() {
        return this.teams_1;
    }

    @Override
    public void setTeams_1(Set<Team> teams_1) {
        this.teams_1 = teams_1;
    }
}
