package Persistence;
// Generated 27.10.2012 15:46:24 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "Role", catalog = "c1teamf")
public class Role implements java.io.Serializable {

    private Integer id;
    private Right right;
    private String name;
    private Set<Member> members = new HashSet(0);

    public Role() {
    }

    public Role(Right right, String name) {
        this.right = right;
        this.name = name;
    }

    public Role(Right right, String name, Set members) {
        this.right = right;
        this.name = name;
        this.members = members;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "right", nullable = false)
    public Right getRight() {
        return this.right;
    }

    @Embedded
    public void setRight(Right right) {
        this.right = right;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "MemberRole", catalog = "c1teamf", joinColumns = {
        @JoinColumn(name = "Role_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "Member_id", nullable = false, updatable = false)})
    public Set<Member> getMembers() {
        return this.members;
    }

    public void setMembers(Set members) {
        this.members = members;
    }
}
