package Persistence;
// Generated 11.11.2012 20:07:48 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RoleRight generated by hbm2java
 */
@Entity
@Table(name = "RoleRight", catalog = "c1teamf")
public class RoleRight implements java.io.Serializable {

    private Integer id;
    private String name;
    private Set<FunctionRole> functionRoles = new HashSet<FunctionRole>(0);

    public RoleRight() {
    }

    public RoleRight(String name) {
        this.name = name;
    }

    public RoleRight(String name, Set functionRoles) {
        this.name = name;
        this.functionRoles = functionRoles;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "roleRight")
    public Set<FunctionRole> getFunctionRoles() {
        return this.functionRoles;
    }

    public void setFunctionRoles(Set<FunctionRole> functionRoles) {
        this.functionRoles = functionRoles;
    }
}
