package CORBA_Competitions;


/**
* CORBA_Competitions/CompetitionsResultsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GetCompetitionResults.idl
* Wednesday, November 14, 2012 1:56:05 PM CET
*/

public interface CompetitionsResultsOperations 
{
  String getCompetitionResults (String liga, String sport, String datum);
} // interface CompetitionsResultsOperations
